version: '2'

services:
    vision-p300:
        image: p300-vision
        network_mode: "host"
        ipc: "host"
        environment:
        - DISPLAY=$DISPLAY
        command: "p300-vision --cid=253 --delay=330"

    eeg-listener:
        image: eeg
        privileged: true
        devices:
          - "/dev/ttyUSB0:/dev/ttyUSB0"
        network_mode: "host"
        command: "eeg --cid=253 --device=/dev/ttyUSB0 --bins=150 --channels=3 --freq=50"
