version: '2'

services:
    eeg-listener:
        image: eeg
        privileged: true
        devices:
          - "/dev/ttyUSB0:/dev/ttyUSB0"
        network_mode: "host"
        command: "eeg --cid=111 --device=/dev/ttyUSB0 --bins=128 --channels=3 --freq=100 --verbose"
